/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Jugador;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class InterfazJuego extends javax.swing.JFrame {

    public InterfazJuego() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
        this.getRootPane().setDefaultButton(jButtonLanzar);
        this.jButtonLanzar.setEnabled(false);
        this.jButtonIniciar.setEnabled(false);
        this.setVisible(true);
    }

    public void mostrarJugadoresEnTabla(ArrayList<Jugador> jugadores) {
        DefaultTableModel modelo = (DefaultTableModel) getTablaJugadores().getModel();
        modelo.setRowCount(0);
        for (Jugador j : jugadores) {
            Object[] row = new Object[5];
            row[0] = j.getNombre();
            row[1] = j.getFicha().getPosicion();
            row[2] = j.getCuenta().getDinero();
            row[3] = j.getCuenta().getPropiedades().size();
            row[4] = j.getEstado();
            modelo.addRow(row);
        }
        getTablaJugadores().setModel(modelo);
        getTablaJugadores().changeSelection(0, 0, false, false);
        centrarDatosTabla(jTableJugadores);
        updateRowHeights(jTableJugadores);
        getTablaJugadores().repaint();
        getTablaJugadores().revalidate();
    }

    
    public final void centrarDatosTabla(JTable t) {
        DefaultTableCellRenderer modeloCentrar = new DefaultTableCellRenderer();
        modeloCentrar.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < t.getColumnCount(); i++) {
            t.getColumnModel().getColumn(i).setCellRenderer(modeloCentrar);
        }

    }

   
    private void updateRowHeights(JTable j) {
        try {
            for (int row = 0; row < j.getRowCount(); row++) {
                int rowHeight = j.getRowHeight();

                for (int column = 0; column < j.getColumnCount(); column++) {
                    Component comp = j.prepareRenderer(j.getCellRenderer(row, column), row, column);
                    rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
                }

                j.setRowHeight(row, (rowHeight + 5));
            }
        } catch (ClassCastException e) {
        }
    }

    public JButton getJButtonLanzar() {
        return this.jButtonLanzar;
    }

    public JTable getTablaJugadores() {
        return this.jTableJugadores;
    }

    public JTextField getJTextFieldUsuario() {
        return jTextFieldUsuario;
    }

    public JButton getJButtonRegistrar() {
        return jButtonRegistrar;
    }

    public JButton getJButtonIniciar() {
        return jButtonIniciar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Tablero = new javax.swing.JPanel();
        Casi1 = new javax.swing.JLabel();
        Casi2 = new javax.swing.JLabel();
        Casi3 = new javax.swing.JLabel();
        Casi4 = new javax.swing.JLabel();
        Casi5 = new javax.swing.JLabel();
        Casi6 = new javax.swing.JLabel();
        Casi7 = new javax.swing.JLabel();
        Casi8 = new javax.swing.JLabel();
        Casi9 = new javax.swing.JLabel();
        Casi10 = new javax.swing.JLabel();
        Casi11 = new javax.swing.JLabel();
        Casi12 = new javax.swing.JLabel();
        Casi13 = new javax.swing.JLabel();
        Casi14 = new javax.swing.JLabel();
        Casi15 = new javax.swing.JLabel();
        Casi16 = new javax.swing.JLabel();
        Casi17 = new javax.swing.JLabel();
        Casi18 = new javax.swing.JLabel();
        Casi19 = new javax.swing.JLabel();
        Casi20 = new javax.swing.JLabel();
        Casi21 = new javax.swing.JLabel();
        Casi22 = new javax.swing.JLabel();
        Casi23 = new javax.swing.JLabel();
        Casi24 = new javax.swing.JLabel();
        Casi25 = new javax.swing.JLabel();
        Casi26 = new javax.swing.JLabel();
        Casi27 = new javax.swing.JLabel();
        Casi28 = new javax.swing.JLabel();
        Casi29 = new javax.swing.JLabel();
        Casi30 = new javax.swing.JLabel();
        Casi31 = new javax.swing.JLabel();
        Casi32 = new javax.swing.JLabel();
        Casi33 = new javax.swing.JLabel();
        Casi34 = new javax.swing.JLabel();
        Casi35 = new javax.swing.JLabel();
        Casi36 = new javax.swing.JLabel();
        Casi37 = new javax.swing.JLabel();
        Casi38 = new javax.swing.JLabel();
        Casi39 = new javax.swing.JLabel();
        Casi40 = new javax.swing.JLabel();
        ConfiguracionGame = new javax.swing.JPanel();
        jButtonLanzar = new javax.swing.JButton();
        jPanelIniciarJuego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        InfoPlayers = new javax.swing.JScrollPane();
        jTableJugadores = new javax.swing.JTable();
        WallpaperLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        Tablero.setBackground(new java.awt.Color(197, 217, 200));
        Tablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Casi1.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Go.png"))); // NOI18N
        Casi1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "1 GO"));
        Casi1.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi1.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi1.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        Casi2.setBackground(java.awt.Color.magenta);
        Casi2.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Casi2.setText("2 Mediterranean Ave. ");
        Casi2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(151, 85, 55), 3));
        Casi2.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi2.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi2.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 70));

        Casi3.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BolsaDinero.png"))); // NOI18N
        Casi3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "3 Arca Común"));
        Casi3.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi3.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi3.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 70));

        Casi4.setBackground(java.awt.Color.magenta);
        Casi4.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi4.setText("4 Bastic Ave.");
        Casi4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(151, 85, 55), 3));
        Casi4.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi4.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi4.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 70));

        Casi5.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi5.setText("5 Impuestos");
        Casi5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Casi5.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi5.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi5.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 70));

        Casi6.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Locomotora.png"))); // NOI18N
        Casi6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "6 Ferrocarril Reading"));
        Casi6.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi6.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi6.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 70));

        Casi7.setBackground(java.awt.Color.green);
        Casi7.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi7.setText("7 Oriental Ave.");
        Casi7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        Casi7.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi7.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi7.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 70));

        Casi8.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/interrogativo.png"))); // NOI18N
        Casi8.setToolTipText("");
        Casi8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "8 Casualidad"));
        Casi8.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi8.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi8.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, 70));

        Casi9.setBackground(java.awt.Color.green);
        Casi9.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi9.setText("9 Vermont Ave.");
        Casi9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        Casi9.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi9.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi9.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, 70));

        Casi10.setBackground(java.awt.Color.green);
        Casi10.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi10.setText("10 Connecticut Ave.");
        Casi10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));
        Casi10.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi10.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi10.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, 70));

        Casi11.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Prision.png"))); // NOI18N
        Casi11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "11 Visita/Carcel"));
        Casi11.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi11.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi11.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, 70));

        Casi12.setBackground(new java.awt.Color(133, 12, 126));
        Casi12.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi12.setText("12 St. Charles Place");
        Casi12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 58, 149), 2));
        Casi12.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi12.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi12.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 90, 70));

        Casi13.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bombillo.png"))); // NOI18N
        Casi13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "13 Compañía Electrica"));
        Casi13.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi13.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi13.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 90, 70));

        Casi14.setBackground(new java.awt.Color(133, 12, 126));
        Casi14.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi14.setText("14 States Ave.");
        Casi14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 58, 149), 2));
        Casi14.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi14.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi14.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 70, 90, 70));

        Casi15.setBackground(new java.awt.Color(133, 12, 126));
        Casi15.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi15.setText("15 Virginia Ave");
        Casi15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 58, 149), 2));
        Casi15.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi15.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi15.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 140, 90, 70));

        Casi16.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Locomotora.png"))); // NOI18N
        Casi16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "16 Ferrocarril Pennsylvania"));
        Casi16.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi16.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi16.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 210, 90, 70));

        Casi17.setBackground(java.awt.Color.orange);
        Casi17.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi17.setText("17 St. James Place");
        Casi17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 147, 33), 2));
        Casi17.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi17.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi17.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 280, 90, 70));

        Casi18.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BolsaDinero.png"))); // NOI18N
        Casi18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "18 Arca Común"));
        Casi18.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi18.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi18.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 350, 90, 70));

        Casi19.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi19.setText("19 Tennessee Ave.");
        Casi19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 147, 33), 2));
        Casi19.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi19.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi19.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 420, 90, 70));

        Casi20.setBackground(java.awt.Color.orange);
        Casi20.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi20.setText("20 New York Ave.");
        Casi20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(247, 147, 33), 2));
        Casi20.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi20.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi20.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 490, 90, 70));

        Casi21.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Parada Libre.png"))); // NOI18N
        Casi21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "21 Parada Libre"));
        Casi21.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi21.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi21.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 560, 90, 70));

        Casi22.setBackground(java.awt.Color.red);
        Casi22.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi22.setText("22 Kentucky Ave.");
        Casi22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Casi22.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi22.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi22.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 560, 90, 70));

        Casi23.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/interrogativo.png"))); // NOI18N
        Casi23.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "23 Casualidad"));
        Casi23.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi23.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi23.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 560, 90, 70));

        Casi24.setBackground(java.awt.Color.red);
        Casi24.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi24.setText("24 Indiana Ave.");
        Casi24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Casi24.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi24.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi24.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi24, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 90, 70));

        Casi25.setBackground(java.awt.Color.red);
        Casi25.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi25.setText("25 Illinois Ave.");
        Casi25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        Casi25.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi25.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi25.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi25, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 90, 70));

        Casi26.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Locomotora.png"))); // NOI18N
        Casi26.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "26 Ferrocarril B&Q"));
        Casi26.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi26.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi26.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi26, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 90, 70));

        Casi27.setBackground(java.awt.Color.yellow);
        Casi27.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi27.setText("27 Atlantic Ave.");
        Casi27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        Casi27.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi27.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi27.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 90, 70));

        Casi28.setBackground(java.awt.Color.yellow);
        Casi28.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi28.setText("28 Ventnor Ave.");
        Casi28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        Casi28.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi28.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi28.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi28, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 90, 70));

        Casi29.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Llave de Agua.png"))); // NOI18N
        Casi29.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "29 Compañía Agua"));
        Casi29.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi29.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi29.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 90, 70));

        Casi30.setBackground(java.awt.Color.yellow);
        Casi30.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi30.setText("30 Marvin Gardens");
        Casi30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        Casi30.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi30.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi30.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 90, 70));

        Casi31.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Police.png"))); // NOI18N
        Casi31.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "31 Ir a la Carcel"));
        Casi31.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi31.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi31.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 90, 70));

        Casi32.setBackground(new java.awt.Color(21, 95, 1));
        Casi32.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi32.setText("32 Pacific Ave.");
        Casi32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 178, 94), 2));
        Casi32.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi32.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi32.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 90, 70));

        Casi33.setBackground(new java.awt.Color(21, 95, 1));
        Casi33.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi33.setText("33 North Carolina Ave.");
        Casi33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 178, 94), 2));
        Casi33.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi33.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi33.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 90, 70));

        Casi34.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BolsaDinero.png"))); // NOI18N
        Casi34.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "34 Arca Común"));
        Casi34.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi34.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi34.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 90, 70));

        Casi35.setBackground(new java.awt.Color(21, 95, 1));
        Casi35.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi35.setText("35 Pennsylvania Ave.");
        Casi35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 178, 94), 2));
        Casi35.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi35.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi35.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 90, 70));

        Casi36.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Locomotora.png"))); // NOI18N
        Casi36.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "36 Ferrocarril Short Line"));
        Casi36.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi36.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi36.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 90, 70));

        Casi37.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/interrogativo.png"))); // NOI18N
        Casi37.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "37 Casualidad"));
        Casi37.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi37.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi37.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 90, 70));

        Casi38.setBackground(new java.awt.Color(15, 1, 104));
        Casi38.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi38.setText("38 Park Place");
        Casi38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 115, 191), 2));
        Casi38.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi38.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi38.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 90, 70));

        Casi39.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Anillo.png"))); // NOI18N
        Casi39.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "39 Impuestos"));
        Casi39.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi39.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi39.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 90, 70));

        Casi40.setBackground(new java.awt.Color(15, 1, 104));
        Casi40.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Casi40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Casi40.setText("40 Boardwalk");
        Casi40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 115, 191), 2));
        Casi40.setMaximumSize(new java.awt.Dimension(90, 20));
        Casi40.setMinimumSize(new java.awt.Dimension(90, 20));
        Casi40.setPreferredSize(new java.awt.Dimension(90, 20));
        Tablero.add(Casi40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 90, 70));

        ConfiguracionGame.setBackground(new java.awt.Color(134, 192, 190));
        ConfiguracionGame.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIVIERTETE!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        ConfiguracionGame.setLayout(new java.awt.GridBagLayout());

        jButtonLanzar.setBackground(new java.awt.Color(134, 192, 190));
        jButtonLanzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dado.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 30;
        ConfiguracionGame.add(jButtonLanzar, gridBagConstraints);

        jPanelIniciarJuego.setBackground(new java.awt.Color(134, 192, 190));
        jPanelIniciarJuego.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Juego", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        jPanelIniciarJuego.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(223, 87, 130));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 25.0;
        gridBagConstraints.weighty = 50.0;
        jPanelIniciarJuego.add(jLabel1, gridBagConstraints);

        jTextFieldUsuario.setBackground(new java.awt.Color(134, 192, 190));
        jTextFieldUsuario.setFont(new java.awt.Font("Ubuntu", 2, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 25.0;
        gridBagConstraints.weighty = 50.0;
        jPanelIniciarJuego.add(jTextFieldUsuario, gridBagConstraints);

        jButtonRegistrar.setBackground(new java.awt.Color(134, 192, 190));
        jButtonRegistrar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 50.0;
        jPanelIniciarJuego.add(jButtonRegistrar, gridBagConstraints);

        jButtonIniciar.setBackground(new java.awt.Color(134, 192, 190));
        jButtonIniciar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 100.0;
        jPanelIniciarJuego.add(jButtonIniciar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 30;
        ConfiguracionGame.add(jPanelIniciarJuego, gridBagConstraints);

        Tablero.add(ConfiguracionGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 510, 130));

        jTableJugadores.setBackground(new java.awt.Color(134, 192, 190));
        jTableJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JUGADOR", "POSICION", "DINERO", "PROPIEDAD", "ESTADO"
            }
        ));
        InfoPlayers.setViewportView(jTableJugadores);

        Tablero.add(InfoPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 420, 400));

        WallpaperLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WallpaperLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Monopoly-Logo-2008 (1).png"))); // NOI18N
        Tablero.add(WallpaperLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 550, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tablero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casi1;
    private javax.swing.JLabel Casi10;
    private javax.swing.JLabel Casi11;
    private javax.swing.JLabel Casi12;
    private javax.swing.JLabel Casi13;
    private javax.swing.JLabel Casi14;
    private javax.swing.JLabel Casi15;
    private javax.swing.JLabel Casi16;
    private javax.swing.JLabel Casi17;
    private javax.swing.JLabel Casi18;
    private javax.swing.JLabel Casi19;
    private javax.swing.JLabel Casi2;
    private javax.swing.JLabel Casi20;
    private javax.swing.JLabel Casi21;
    private javax.swing.JLabel Casi22;
    private javax.swing.JLabel Casi23;
    private javax.swing.JLabel Casi24;
    private javax.swing.JLabel Casi25;
    private javax.swing.JLabel Casi26;
    private javax.swing.JLabel Casi27;
    private javax.swing.JLabel Casi28;
    private javax.swing.JLabel Casi29;
    private javax.swing.JLabel Casi3;
    private javax.swing.JLabel Casi30;
    private javax.swing.JLabel Casi31;
    private javax.swing.JLabel Casi32;
    private javax.swing.JLabel Casi33;
    private javax.swing.JLabel Casi34;
    private javax.swing.JLabel Casi35;
    private javax.swing.JLabel Casi36;
    private javax.swing.JLabel Casi37;
    private javax.swing.JLabel Casi38;
    private javax.swing.JLabel Casi39;
    private javax.swing.JLabel Casi4;
    private javax.swing.JLabel Casi40;
    private javax.swing.JLabel Casi5;
    private javax.swing.JLabel Casi6;
    private javax.swing.JLabel Casi7;
    private javax.swing.JLabel Casi8;
    private javax.swing.JLabel Casi9;
    private javax.swing.JPanel ConfiguracionGame;
    private javax.swing.JScrollPane InfoPlayers;
    private javax.swing.JPanel Tablero;
    private javax.swing.JLabel WallpaperLogo;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonLanzar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelIniciarJuego;
    private javax.swing.JTable jTableJugadores;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
